:toc: macro
:toclevels: 5
:figure-caption!:

:htmx_link: link:https://htmx.org[htmx]

= htmx Slide

This library is a {htmx_link} link:https://htmx.org/extensions[extension] that can be used for rendering slidedhows.

toc::[]

== Features

* Allows you to render slideshows with View Transitions.

== Screencasts

video::https://alchemists.io/videos/projects/htmx-slide/demo.mp4[poster=https://alchemists.io/images/projects/htmx-slide/demo.png,width=790,height=508,role=focal_point]

== Requirements

. {htmx_link}.
. link:https://nodejs.org[Node] (optional, for development).
. link:https://www.ruby-lang.org[Ruby] (optional, for development).

== Setup

The following _assumes_ you are already using {htmx_link} and have it configured in the same manner as documented in this setup section.

To use via the HTML `script` element, add the following to your layout:

[source,html]
----
<script src="https://unpkg.com/htmx-slide@latest"
        integrity="sha384-m5FEt832hzXVEPKT4pjAfi1eiFHSXKZDpsPOCzBOLmd9ycRm+QAIFU+/CZflfRyq"
        crossorigin="anonymous">
</script>
----

To use via Import Maps, add the following to your layout:

[source,html]
----
<script type="importmap">
  {
    "imports": {
      "htmx-slide": "https://unpkg.com/htmx-slide@latest"
    }
  }
</script>

<script type="module">
  import "htmx-slide";
</script>
----

To install via link:https://www.npmjs.com[NPM], run:

[source,bash]
----
npm install htmx-slide
----

Once the library is installed, you only need to import it:

[source,js]
----
import "htmx-slide";
----

== Usage

To use, implement a select element with option values that provide URLs to templates or partials. Example:

[source,html]
----
----

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/htmx-slide
cd htmx-slide
bin/setup
----

To build, run:

[source,bash]
----
bin/build
----

To view interactive demonstration, run

[source,bash]
----
# With default port.
bin/demo

# With custom port.
bin/demo 9050
----

== Tests

To test, run:

[source,bash]
----
bin/rake
----

== Deployment

To deploy, follow these steps:

. Ensure link:https://alchemists.io/projects/milestoner[Milestoner] is installed.
. Ensure you are on the `main` branch.
. Run the following:

[source,bash]
----
bin/build
npm publish
milestoner --publish
----

== link:https://alchemists.io/policies/license[License]

== link:https://alchemists.io/policies/security[Security]

== link:https://alchemists.io/policies/code_of_conduct[Code of Conduct]

== link:https://alchemists.io/policies/contributions[Contributions]

== link:https://alchemists.io/policies/developer_certificate_of_origin[Developer Certificate of Origin]

== link:https://alchemists.io/projects/htmx-slide/versions[Versions]

== link:https://alchemists.io/community[Community]

== Credits

* Built with link:https://alchemists.io/projects/rubysmith[Rubysmith].
* Engineered by link:https://alchemists.io/team/brooke_kuhlmann[Brooke Kuhlmann].
